[options]
addons_path = /Users/joel/Desktop/wds-dir/fact/odoo-19.0/addons,/Users/joel/Desktop/wds-dir/fact/odoo-19.0/odoo/addons,/Users/joel/Desktop/wds-dir/fact/odoo-ne-integration/addons
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8169
admin_passwd = admin123
list_db = True
